name: floor_annotation
description: >
  The typesafe, reactive, and lightweight SQLite abstraction for your Flutter applications.
  Don't use this package directly. Import the floor package instead.
version: 1.0.1
homepage: https://floor.codes

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: 1.9.1
