name: floor_generator
description: >
  The typesafe, reactive, and lightweight SQLite abstraction for your Flutter applications.
  This library is the dev dependency.
version: 1.2.0
homepage: https://floor.codes
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  analyzer: '>=5.12.0 <7.0.0'
  build: 2.4.1
  build_config: 1.1.1
  code_builder: 4.10.0
  collection: 1.18.0
  floor_annotation:
    path: ../floor_annotation/
  meta: 1.12.0
  source_gen: 1.5.0
  strings: 3.1.1
  sqlparser: 0.36.0

dev_dependencies:
  build_test: 2.2.2
  dart_style: 2.3.6
  mockito: 5.4.4
  path: 1.9.0
  test: 1.25.2
  test_cov: 1.0.1
