name: floor_generator
description: >
  The typesafe, reactive, and lightweight SQLite abstraction for your Flutter applications.
  This library is the dev dependency.
version: 1.2.0
homepage: https://floor.codes
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: '>=5.12.0 <7.0.0'
  build: 2.4.1
  build_config: 1.1.1
  code_builder: 4.5.0
  collection: 1.17.1
  floor_annotation:
    path: ../floor_annotation/
  meta: 1.9.1
  source_gen: 1.4.0
  strings: 2.0.2
  sqlparser: 0.30.3

dev_dependencies:
  build_test: 2.2.0
  dart_style: 2.3.2
  mockito: 5.4.2
  path: 1.8.3
  test: 1.24.4
  test_cov: 1.0.1
