name: example
description: >
  The typesafe, reactive and lightweight SQLite abstraction for your Flutter applications.
  This is an example on how to use the library.
version: 1.0.0
homepage: https://floor.codes
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  floor:
    path: ../floor/
  flutter:
    sdk: flutter

dev_dependencies:
  analyzer: '>=5.12.0 <7.0.0'
  build_runner: 2.4.6
  floor_generator:
    path: ../floor_generator/
  flutter_test:
    sdk: flutter
