name: floor
description: >
  The typesafe, reactive, and lightweight SQLite abstraction for your Flutter applications.
  This library is the runtime dependency.
version: 1.2.0
homepage: https://floor.codes
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  floor_annotation:
    path: ../floor_annotation/
  flutter:
    sdk: flutter
  meta: 1.9.1
  path: 1.8.3
  sqflite: 2.2.8+4
  sqflite_common_ffi: 2.2.5

dev_dependencies:
  build_runner: 2.4.6
  collection: 1.17.1
  floor_generator:
    path: ../floor_generator/
  flutter_test:
    sdk: flutter
  matcher: 0.12.15
  mockito: 5.4.2
