name: floor
description: >
  The typesafe, reactive, and lightweight SQLite abstraction for your Flutter applications.
  This library is the runtime dependency.
version: 1.2.0
homepage: https://floor.codes
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  floor_annotation:
    path: ../floor_annotation/
  flutter:
    sdk: flutter
  meta: 1.12.0
  path: 1.9.0
  sqflite: 2.3.3+1
  sqflite_common_ffi: 2.3.2+1

dev_dependencies:
  build_runner: 2.4.8
  collection: 1.18.0
  floor_generator:
    path: ../floor_generator/
  flutter_test:
    sdk: flutter
  matcher: 0.12.16+1
  mockito: 5.4.4
